# GOAD / NHA
sql_instance_name: SQLEXPRESS
sql_version: MSSQL_2019

# SCCM
#sql_instance_name: MSSQLSERVER
#sql_version: MSSQL_2022

download_url_2019: https://download.microsoft.com/download/7/f/8/7f8a9c43-8c8a-4f7c-9f92-83c18d96b681/SQL2019-SSEI-Expr.exe
download_url_2022: https://download.microsoft.com/download/5/1/4/5145fe04-4d30-4b85-b0d1-39533663a2f1/SQL2022-SSEI-Expr.exe

connection_type_2019: "-b -E -S localhost\\SQLEXPRESS"
connection_type_2022: "-b -S 127.0.0.1,1433"
