---
galaxy_info:
  role_name: sccm_config_accounts
  namespace: dreadnode
  author: Dreadnode
  company: Dreadnode
  description: Configure SCCM service accounts and permissions
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - sccm
    - mecm
    - accounts
    - configuration

dependencies: []
