---
galaxy_info:
  role_name: common
  namespace: dreadnode
  author: Dreadnode
  company: Dreadnode
  description: Apply common Windows configuration settings for domain-joined hosts
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - configuration
    - dns
    - common

dependencies: []
