---
galaxy_info:
  role_name: mssql_ssms
  namespace: dreadnode
  author: Dreadnode
  company: Dreadnode
  description: Install SQL Server Management Studio
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - mssql
    - ssms
    - management

dependencies: []
