---
- name: Refresh
  ansible.windows.win_command: gpupdate /force

- name: Copy ADCSTemplate zip to remote
  ansible.windows.win_copy:
    src: files/ADCSTemplate.zip
    dest: "C:\\Windows\\Temp\\ADCSTemplate.zip"

- name: Extract ADCSTemplate module
  ansible.windows.win_shell: |
    $destPath = "C:\Program Files\WindowsPowerShell\Modules\ADCSTemplate"
    if (Test-Path $destPath) {
        Remove-Item -Path $destPath -Recurse -Force
    }
    Expand-Archive -Path "C:\Windows\Temp\ADCSTemplate.zip" -DestinationPath "C:\Program Files\WindowsPowerShell\Modules" -Force
    Remove-Item -Path "C:\Windows\Temp\ADCSTemplate.zip" -Force

- name: Create a directory for templates
  ansible.windows.win_file:
    path: c:\setup
    state: directory

- name: Install templates
  ansible.windows.win_shell: |
    if (-not(Get-ADCSTemplate -DisplayName "{{ item.value.template_name }}")) { New-ADCSTemplate -DisplayName "{{ item.value.template_name }}" -JSON (Get-Content {{ item.value.template_file }} -Raw) -Identity "{{ domain_name }}\Domain Users" -Publish }
  vars:
    ansible_become: true
    ansible_become_method: ansible.builtin.runas
    domain_name: "{{ domain }}"
    ansible_become_user: "{{ domain_username }}"
    ansible_become_password: "{{ domain_password }}"
  with_dict: "{{ vulns_vars }}"
