---
- name: Set configure dns
  ansible.windows.win_dns_client:
    adapter_names: "{{ domain_adapter }}"
    ipv4_addresses:
    - "{{ hostvars[dns_domain].ansible_host }}"
    log_path: C:\dns_log.txt

- name: Promote the server to additional DC
  microsoft.ad.domain_controller:
    dns_domain_name: "{{ domain_name }}"
    domain_admin_user: "{{ domain_username }}"
    domain_admin_password: "{{ domain_password }}"
    safe_mode_password: "{{ domain_password }}"
    state: domain_controller
    log_path: C:\ansible_win_domain_controller.txt
    reboot: true
  register: check_domain_controller
  failed_when:
    - check_domain_controller is failed
    - '"already a domain controller" not in check_domain_controller.msg | default("")'
