---
galaxy_info:
  role_name: dns_conditional_forwarder
  namespace: dreadnode
  author: Dreadnode
  company: Dreadnode
  description: Configure DNS conditional forwarders on member servers
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - dns
    - forwarder
    - networking

dependencies: []
