---
galaxy_info:
  role_name: sccm_install_adk
  namespace: dreadnode
  author: Dreadnode
  company: Dreadnode
  description: Install Windows Assessment and Deployment Kit for SCCM
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - sccm
    - mecm
    - adk
    - installation

dependencies: []
