---
galaxy_info:
  role_name: security_enable_run_as_ppl
  namespace: dreadnode
  author: Dreadnode
  company: Dreadnode
  description: Enable LSA Protection (RunAsPPL) for credential hardening
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - security
    - lsa
    - hardening
    - credentials

dependencies: []
