---
galaxy_info:
  role_name: vulns_files
  namespace: dreadnode
  author: Dreadnode
  company: Dreadnode
  description: Deploy sensitive files to hosts for attack simulation
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - vulnerability
    - files
    - pentest

dependencies: []
