---
galaxy_info:
  role_name: sccm_install_prerequisites
  namespace: dreadnode
  author: Dreadnode
  company: Dreadnode
  description: Install SCCM prerequisites including System Management container
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - sccm
    - mecm
    - prerequisites
    - installation

dependencies: []
