---
galaxy_info:
  role_name: vulns_enable_nbt_ns
  namespace: dreadnode
  author: Dreadnode
  company: Dreadnode
  description: Enable NetBIOS Name Service for poisoning attack simulation
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - vulnerability
    - nbt_ns
    - pentest
    - poisoning

dependencies: []
