---
galaxy_info:
  role_name: mssql_audit
  namespace: dreadnode
  author: Dreadnode
  company: Dreadnode
  description: Configure SQL Server auditing for security monitoring
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - mssql
    - audit
    - security

dependencies: []
