---
galaxy_info:
  role_name: vulns_credentials
  namespace: dreadnode
  author: Dreadnode
  company: Dreadnode
  description: Store credentials in Windows Credential Manager for attack simulation
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - vulnerability
    - credentials
    - pentest

dependencies: []
