---

# set AD data ==================================================================================================
# child
- name: Child DC AD configuration
  hosts: child_dc
  gather_facts: false
  roles:
    - { role: 'dreadnode.goad.child_domain', tags: 'child_domain'}
    - { role: 'dreadnode.goad.dns_conditional_forwarder', tags: 'dns_conditional_forwarder' }
  vars:
    domain: "{{ lab.hosts[dict_key].domain }}"
    domain_password: "{{ lab.domains[domain].domain_password }}"
    netbios_name: "{{ lab.domains[domain].netbios_name }}"
    parent_domain: "{{ '.'.join(domain.split('.')[1:]) }}"
    parent_domain_user: "{{ admin_user }}@{{ parent_domain }}"
    parent_domain_password: "{{ lab.domains[parent_domain].domain_password }}"
    source_dc: "{{ lab.hosts[lab.domains[parent_domain].dc].hostname }}.{{ parent_domain }}"
    zone_name: "{{ parent_domain }}"
    remote_dc: "{{ lab.domains[parent_domain].dc }}"
    instance_to_ip: "{{ hostvars[groups['dc'][0]]['instance_to_ip'] | default({}) }}"
    master_server: "{{ hostvars[remote_dc]['dc_ipv4'] | default(instance_to_ip[hostvars[remote_dc]['ansible_host']] | default(hostvars[remote_dc].ansible_host)) }}"
    replication: none

- name: Parent DC ADD DNS configuration
  hosts: parent_dc
  gather_facts: false
  roles:
    - { role: 'dreadnode.goad.parent_child_dns', tags: 'parent_child_dns'}
  vars:
    domains: "{{ lab.domains.keys() }}"
    domain: "{{ lab.hosts[dict_key].domain }}"
    dc_hostname_to_ip: "{{ hostvars[groups['dc'][0]]['dc_hostname_to_ip'] | default({}) }}"
    instance_to_ip: "{{ hostvars[groups['dc'][0]]['instance_to_ip'] | default({}) }}"
