# LOGS and Monitoring ==========================================================================================
- name: Install ELK
  hosts: elk_server
  become: true
  roles:
    - { role: 'dreadnode.goad.elk', tags: 'elk' }

- name: Install log agent on windows vms
  hosts: elk_log
  roles:
    - { role: 'dreadnode.goad.logs_windows', tags: 'agent' }
