---
# Extension: exchange — Add Exchange Server to GOAD lab

- name: Read extension config file
  hosts: domain:extensions
  connection: local
  vars_files:
    - "{{ extension_data_dir }}/config.json"
  tasks:
    - name: merge lab variable with extension config
      set_fact:
        lab: "{{ lab|combine(lab_extension, recursive=True) }}"

- name: Update AD data
  hosts: dc01
  roles:
    - { role: 'dreadnode.goad.ad', tags: 'ad_domain_data' }
  vars:
    hostname: "{{lab.hosts[dict_key].hostname}}"
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{domain}}\\{{admin_user}}"
    domain_password: "{{lab.domains[domain].domain_password}}"
    domain_server: "{{lab.hosts[dict_key].hostname}}.{{domain}}"
    ad_users: "{{lab.domains[lab.hosts[dict_key].domain].users}}"
    ad_ou: "{{lab.domains[lab.hosts[dict_key].domain].organisation_units  | default({}) }}"
    ad_groups: "{{lab.domains[lab.hosts[dict_key].domain].groups}}"

- name: Install new server
  hosts: srv01
  roles:
    - { role: 'dreadnode.goad.common', tags: 'common', http_proxy: "{{enable_http_proxy}}" }
    - { role: 'dreadnode.goad.settings_keyboard', tags: 'keyboard', layouts: "{{keyboard_layouts}}" }
    - { role: 'dreadnode.goad.settings_no_updates', tags: 'no_updates' }
    - { role: 'dreadnode.goad.settings_admin_password', tags: 'admin_password' }
    - { role: 'dreadnode.goad.settings_hostname', tags: 'hostname' }
    - { role: 'dreadnode.goad.member_server', tags: 'server' }
    - { role: 'dreadnode.goad.settings_adjust_rights', tags: 'adjust_rights' }
    - { role: 'dreadnode.goad.settings_user_rights', tags: 'adjust_rights' }
  vars:
    local_admin_password: "{{lab.hosts[dict_key].local_admin_password}}"
    hostname: "{{lab.hosts[dict_key].hostname}}"
    member_domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{member_domain}}\\{{admin_user}}"
    domain_password: "{{lab.domains[member_domain].domain_password}}"
    local_groups: "{{lab.hosts[dict_key].local_groups  | default({}) }}"

- name: Synchronize all domains
  hosts: dc
  roles:
    - { role: 'dreadnode.goad.sync_domains', tags: 'sync' }
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{domain}}\\{{admin_user}}"
    domain_password: "{{lab.domains[domain].domain_password}}"

- name: Install exchange
  hosts: srv01
  roles:
    - { role: 'dreadnode.goad.ludus_exchange', tags: 'exchange' }
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    ludus_exchange_domain: "{{domain.split('.')[0]}}"
    ludus_exchange_dc: "{{lab.hosts[dict_key].hostname}}.{{domain}}"
    ludus_exchange_host: "{{lab.hosts[dict_key].hostname}}"
    ludus_exchange_domain_username: "{{domain}}\\{{admin_user}}"
    ludus_exchange_domain_password: "{{lab.domains[domain].domain_password}}"
    ludus_os_version: "2019"
    ludus_exchange_iso_directory: "C:\\exchange"
    exchange_prereqs_complete_file: "{{ ludus_exchange_iso_directory }}\\exchange_prereqs_complete.txt"
    send_connector_source_transport_servers: "{{ludus_exchange_host}}"
    ludus_install_directory: "./iso"

- name: Add exchange mail reader bot
  hosts: srv01
  roles:
    - { role: 'dreadnode.goad.exchange_bot', tags: 'exchange_bot' }
