---

# Network discovery (lab config loaded automatically by vars plugin)
- name: Import Network Setup
  ansible.builtin.import_playbook: network_setup.yml
  tags: 'network_setup'

# Prepare servers
- name: Import Build
  ansible.builtin.import_playbook: build.yml
# Add monitoring
#- ansible.builtin.import_playbook: elk.yml

# --------------------------------------------------------------------
# VM ready - start insert specific scenario
# --------------------------------------------------------------------
# Turn server into DC and load active directory data (users/groups/ou)
#- ansible.builtin.import_playbook: ad.yml
# create main domains, child domain and enroll servers

## AD ----------
- name: Import Ad Servers
  ansible.builtin.import_playbook: ad-servers.yml
- name: Import Ad Parent Domain
  ansible.builtin.import_playbook: ad-parent_domain.yml
- name: Import Ad Child Domain
  ansible.builtin.import_playbook: ad-child_domain.yml
- name: Import Ad Members
  ansible.builtin.import_playbook: ad-members.yml
# create the trust relationships
- name: Import Ad Trusts
  ansible.builtin.import_playbook: ad-trusts.yml
# import the ad data: users/groups...
- name: Import Ad Data
  ansible.builtin.import_playbook: ad-data.yml
# set the GMAS accounts
- name: Import Ad Gmsa
  ansible.builtin.import_playbook: ad-gmsa.yml
# install LAPS
- name: Import Laps
  ansible.builtin.import_playbook: laps.yml
- name: Import Localusers
  ansible.builtin.import_playbook: localusers.yml
## MSSQL + IIS  ----------
# configure servers vulns (done in the middle of ad install to let time before install relations and acl)
#- ansible.builtin.import_playbook: servers.yml
## AD - servers localgroup + rdp + inter domain relations & acl
# set the rights and the group domains relations
- name: Import Ad Relations
  ansible.builtin.import_playbook: ad-relations.yml
# set adcs
- name: Import Adcs
  ansible.builtin.import_playbook: adcs.yml
# set the ACL
- name: Import Ad Acl
  ansible.builtin.import_playbook: ad-acl.yml

## SERVERS ---------
### MSSQL + IIS  ----------
# configure servers vulns (done in the middle of ad install to let time before install relations and acl)
- name: Import Servers
  ansible.builtin.import_playbook: servers.yml

## SECURITY -----
# --------------------------------------------------------------------
# specifics security linked to the scenario are here
- name: Import Security
  ansible.builtin.import_playbook: security.yml
# --------------------------------------------------------------------
# specifics vulns linked to the scenario are here
- name: Import Vulnerabilities
  ansible.builtin.import_playbook: vulnerabilities.yml

- name: Import Reboot
  ansible.builtin.import_playbook: reboot.yml
