---

- name: Setup vulnerabilities with tasks
  hosts: domain
  tasks:
    - name: "Include vulnerability role"
      ansible.builtin.include_role:
        name: "dreadnode.goad.vulns_{{ vuln }}"
      vars:
        vulns_vars: "{{ lab.hosts[dict_key].vulns_vars[vuln] | default({}) }}"
        domain: "{{ lab.hosts[dict_key].domain }}"
        domain_username: "{{ domain }}\\{{ admin_user }}"
        domain_password: "{{ lab.domains[domain].domain_password }}"
      loop: "{{ lab.hosts[dict_key].vulns | default([]) }}"
      loop_control:
        loop_var: vuln
        label: "{{ vuln }}"

    - name: "Include PowerShell script role"
      ansible.builtin.include_role:
        name: "dreadnode.goad.ps"
      vars:
        script_path: "{{ playbook_dir }}/../../ad/{{ domain_name }}/scripts"
        ps_script: "{{ script_path }}/{{ item }}"
      loop: "{{ lab.hosts[dict_key].scripts | default([]) }}"
