---
- name: Install ADCS
  ansible.windows.win_feature:
    name: AD-Certificate
    state: present
    include_sub_features: true
    include_management_tools: true
  register: win_feature

- name: Install-WindowsFeature ADCS-Cert-Authority
  ansible.windows.win_feature:
    name: ADCS-Cert-Authority
    state: present
    include_management_tools: true

- name: Install-WindowsFeature ADCS-Web-Enrollment
  ansible.windows.win_feature:
    name: ADCS-Web-Enrollment
    state: present
  when: ca_web_enrollment

- name: Install-ADCSCertificationAuthority-PS
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param (
          [String]
          $domain_username,
          [String]
          $domain_password,
          [String]
          $ca_common_name
      )
      $pass = ConvertTo-SecureString $domain_password -AsPlainText -Force
      $Cred = New-Object System.Management.Automation.PSCredential ($domain_username, $pass)
      try {
        Install-AdcsCertificationAuthority -Credential $Cred -CAType EnterpriseRootCA -CryptoProviderName "RSA#Microsoft Software Key Storage Provider" -KeyLength 2048 -HashAlgorithmName SHA256 -ValidityPeriod Years -ValidityPeriodUnits 5 -CACommonName $ca_common_name -Force
        $Ansible.Changed = $true
      } catch {
        $Ansible.Changed = $false
      }
    error_action: stop
    parameters:
      domain_username: "{{ domain_username }}"
      domain_password: "{{ domain_password }}"
      ca_common_name: "{{ ca_common_name }}"
  async: 1800
  poll: 60

# ESC 8
# ignore error if already installed
- name: Enable Web enrollement
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding()]
      param ()
      try {
        Install-AdcsWebEnrollment -Force
        $Ansible.Changed = $true
      } catch {
        $Ansible.Changed = $false
      }
  when: ca_web_enrollment
  async: 1800
  poll: 60

- name: Refresh Group Policy
  ansible.windows.win_shell: |
    try {
      Write-Output "Attempting to update group policy..."
      $result = gpupdate /force
      Write-Output "Group policy update command executed."
      exit 0
    } catch {
      Write-Output "Error during GPUpdate: $_"
      # Return success even if GPUpdate failed
      # This makes the task idempotent
      exit 0
    }
  failed_when: false

# - name: Reboot after ADCS installation
#   win_reboot:
#   when: win_feature.reboot_required
