---
galaxy_info:
  role_name: security_ensure_kb_not_installed
  namespace: dreadnode
  author: Dreadnode
  company: Dreadnode
  description: Ensure specific Windows KB updates are not installed
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - security
    - updates
    - hardening

dependencies: []
