---
galaxy_info:
  role_name: settings_enable_nat_adapter
  namespace: dreadnode
  author: Dreadnode
  company: Dreadnode
  description: Enable the NAT network adapter on Windows hosts
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - networking
    - configuration

dependencies: []
