---
galaxy_info:
  role_name: settings_no_updates
  namespace: dreadnode
  author: Dreadnode
  company: Dreadnode
  description: Disable Windows Update service to preserve lab state
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - configuration
    - updates

dependencies: []
