---
# https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc835086(v=ws.11)
- name: "Synchronizes all domains before change schema"
  ansible.windows.win_shell: repadmin /syncall /AdePq
  vars:
    ansible_become: true
    ansible_become_method: ansible.builtin.runas
    ansible_become_user: "{{ domain_username }}"
    ansible_become_password: "{{ domain_password }}"
