---
galaxy_info:
  role_name: vulns_autologon
  namespace: dreadnode
  author: Dreadnode
  company: Dreadnode
  description: Configure Windows autologon credentials for attack simulation
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - vulnerability
    - autologon
    - credentials
    - pentest

dependencies: []
