---
# DNSCHANGE
- name: Prioritize the domain interface as the default for routing
  ansible.windows.win_shell:
    Set-NetIPInterface -InterfaceAlias "{{ domain_adapter }}" -InterfaceMetric 10
  when: two_adapters | default(false) | bool

# Debug the IP
- name: Debug the DNS server IP
  ansible.builtin.debug:
    msg: "DNS Server IP: {{ dns_server_ip | default('empty/failed') }}"

- name: Set configure dns to {{ dns_domain }}
  ansible.windows.win_dns_client:
    adapter_names: "{{ domain_adapter }}"
    ipv4_addresses:
    - "{{ dns_server_ip }}"
    log_path: C:\dns_log.txt

- name: Add workstation to {{ member_domain }}
  microsoft.ad.membership:
    dns_domain_name: "{{ member_domain }}"
    domain_admin_user: "{{ domain_username }}"
    domain_admin_password: "{{ domain_password }}"
    state: domain
  register: domain_state
  async: 1800
  poll: 60
  failed_when: false

- name: Reboot if needed
  ansible.windows.win_reboot:
    reboot_timeout: 1500
    post_reboot_delay: 100
  when: domain_state is changed and (domain_state.reboot_required | default(false))
