---
galaxy_info:
  role_name: groups_domains
  namespace: dreadnode
  author: Dreadnode
  company: Dreadnode
  description: Create and configure Active Directory groups across domains
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - windows
    - active_directory
    - groups
    - domain

dependencies: []
