---
- name: Add DNS server zone
  ansible.windows.win_dns_zone:
    name: "{{ item }}"
    type: forwarder
    replication: "{{ replication }}"
    dns_servers:
      - "{{ hostvars[dc]['dc_ipv4'] | default(instance_to_ip[hostvars[dc]['ansible_host']] if hostvars[dc]['ansible_host'] in instance_to_ip else hostvars[dc].ansible_host) }}"
  vars:
    ansible_become: true
    ansible_become_method: ansible.builtin.runas
    ansible_become_user: "{{ domain_username }}"
    ansible_become_password: "{{ domain_password }}"
    dc: "{{ lab.domains[item].dc }}"
  loop: "{{ domains }}"
  when: item != domain and item != trust and item != parent_domain and '.'.join(item.split('.')[1:]) != domain
