---
name: Tests
on:
  merge_group:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  GO_VERSION: "1.26.2"

permissions:
  actions: read
  checks: write
  contents: read
  pull-requests: write

jobs:
  tests:
    name: Run Go tests and determine code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: Generate the coverage output
        run: |
          bash .hooks/run-go-tests.sh coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: coverage-report
          path: cli/coverage-all.out
          retention-days: 14
