---
name: Tests
on:
  merge_group:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  GO_VERSION: "1.26.3"

permissions:
  actions: read
  checks: write
  contents: read
  pull-requests: write

jobs:
  tests:
    name: Run Go tests and determine code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: Generate the coverage output
        run: |
          bash .hooks/run-go-tests.sh coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: coverage-report
          path: cli/coverage-all.out
          retention-days: 14
